### ISSUE TITLE
Add confirmation check for downloading/installing large amount of data

### ISSUE THREAD

**Issue by qmac** [neuroscout/neuroscout-cli#12]
Currently, the CLI will just download all needed files. However, it would be nice to get confirmation that the user intends to download the specified files, given that it could potentially be time-consuming.

**Comment by adelavega** [comment]
Maybe datalad can help with estimating the number of files / size of files that need to be downloaded.

**Comment by adelavega** [comment]
since datalad shows this pretty clearly, and you can cancel anytime, I'm going to close this
