### ISSUE TITLE
Re-configure directory defaults

### ISSUE THREAD

**Issue by adelavega** [neuroscout/neuroscout-cli#124]
I'm seeking feedback to see if I should change the default directory mappings in Neuroscout, to be more polite to Singularity users (where the filesystem is automatically mapped). 

Current defaults:
 - `outdir` - not specified mandatory
 - `workdir` - None, fitlins defaults to a `/tmp` dir
 - `install_dir` (where data is downloaded using datalad). default is : '.' / current directory. In a docker image that is `/work`, in singularity its where script is executed (i.e. sbatch).

Perhaps a more sensible default would be to use `/tmp` dirs for both, or to force them to be set (or at least the data directory). 

Another consideration is whether or not an `output` directory should be mandatory. Currently it is, but if someone wanted to run and just upload results to neurovault, none of these directories should be necessary as the job is fully self contained.

**Comment by adelavega** [comment]
Actually, one additional consideration is where to store bundles. Ideally it would not be in the `install_dir` so that can be a clean set of datasets. I may add one more CLI flag for this.

**Comment by effigies** [comment]
What if the default is to create a `./neuroscout-<bundleid>` with `bundle/` `data/` and `out/`? (If you want to do it YODA-style, you could make `outdir` the `./neuroscout-<bundleid>` and use `inputs/bundle` + `inputs/data`. Or something of that sort.)

**Comment by jdkent** [comment]
Adding on, the current working directory could either be `/home/neuro` or a root `/neuroscout-work` directory that is unlikely to be automatically/unsuspectingly mapped to the host filesystem unless the user specifically specifies a bind. (The root directory is likely the safer bet since in my experience roots directories are unlikely to be over-populated with randomly named folders)

**Comment by adelavega** [comment]
I like that and I think what you're proposing is more reproducible but consider another (admitted self serving) consideration:


I like the idea of keeping input preproc separate from bundles/specific analyses. This makes it easier to re-use the input data for other uses without mixing in bundles. That way you could cache the data and use it for other neuroscout analyses or other analyses in general. 

I say self serving bc running on TACC (where the source data for the datalad datasets actually lives), it would be nice to just point neuroscout to that folder and not have to download anything except a bundle.

Here's a proposal that mixes our suggestions:

- outdir defaults to `./neuroscout-<bundleid>` and contains `/out` and `/bundle` (containing unzipped bundle). 
- `install_dir` (may better if I rename it `data_dir`) defaults to `'./neuroscout-datasets` and contains folders matching the available repositories here: `https://github.com/neuroscout-datasets/`

An additional consideration is what if you re-run an analysis with different cli flags? Perhaps we check to se if `neuroscout-<bundleid>/out` exists, and if it does then create  `neuroscout-<bundleid>/out[n+1]` as the outdir

**Comment by adelavega** [comment]
Actually, technically speaking `outdir` would defaul to `.` but would create a `neuroscout-<bundleid>` folder within the folder it pointed towards. and maybe within it its better to call `/out` just `/fitlins`

**Comment by adelavega** [comment]
@jdkent to your suggestion, I think for `workdir` I will map it to `mkdtemp` folder (or rather, to None and `fitlins` will do that).

**Comment by effigies** [comment]
I don't have strong opinions here, so go with something that suits your needs. I would just consider making it possible to do a full YODA case where all inputs can be a subdataset of the outputs, even if it's not the default.

**Comment by adelavega** [comment]
@jdkent I think to solve the unsuspecting mapping, any folder that is not explicitly defined (i.e. `install_dir`) would default to a tmpdir as defined by `mkdtemp`, does that work for you or will it behave well in HPC clusters? We could also make it mandatory

**Comment by adelavega** [comment]
@effigies I agree. Perhaps here's the thing that ties all of these concerns together. If `install_dir` is not defined (perhaps better called `cache_dir`), then it defaults to `YODA` operation as you suggested. 

That is:
`neuroscout-<bundle-id>`
   - `/out`
   - `/bundle`
   - `/data`
   
If `cache_dir` is defined, then `/data` is not created and is read from other other directory. 

This way, there's also no undefined directories that we have to magically map.

**Comment by adelavega** [comment]
We could even potentially keep the `/data` in all instances but make it a symlink if `cache_dir` is defined

**Comment by adelavega** [comment]
Okay I like this, thanks for the feedback I think it's better than what was in my head! I'm going to draft this up and make a PR, I would appreciate a review :)
