### ISSUE TITLE
Add config file

### ISSUE THREAD

**Issue by qmac** [neuroscout/neuroscout-cli#15]
Where the user can specify things like neuroscout remote server address.

**Comment by adelavega** [comment]
In deployment for 99% of users it will be hardcoded, so I think its ok to version control this file (sometimes you dont wanna do that w/ config files). But if there are any sensitive info we should probably put that somewhere else (or in env vars)

**Comment by adelavega** [comment]
I'm closing this until I have a specific reason to need it. Probably best to have it all through the api. pyns will have its own config perhaps.
