### ISSUE TITLE
Collect fitlins outputs and push to NeuroVault

### ISSUE THREAD

**Issue by adelavega** [neuroscout/neuroscout-cli#18]
The `pynv` library supports pushing to NeuroVault. Given security concerns, we will not cache credentials, and instead prompt users to enter their usename and password for pushing. We can also use a neuroscout account to push all results if no credentials are entered / found. 

By default, we can push all stat maps

**Comment by adelavega** [comment]
This might be better to do in fitlins, so we have better access to metadata.

**Comment by adelavega** [comment]
See: https://github.com/neuroscout/neuroscout/issues/196

**Comment by adelavega** [comment]
I'm trying to think through the security implications of uploading images / reports of execution.

I'm going to break it down into two types of information: images and execution metadata.

In terms of images, we have two options: 
1) Upload to user's account. We can ask users to log in to NeuroVault (either interactively, through a log in file, or through an environment variable. The main downside is that this is another burden to jump through to upload images, so this seems like a bad idea, as wed like to automate as much of the uploading as possible

2) Upload to a NeuroScout account/collection on NeuroVault. User's would not have to log into NeuroVault as some common key by a NeuroScout user would be used. Now the question becomes how to handle these keys securely. We need some sort of authentication system, so only valid images are posted to NeuroVault. One option is that NeuroScout API could be a third party authenticator, and get API keys to CLI clients while holding securely the auth keys. That is, the `neuroscout-cli` would require users to log in, and then be granted a neurovault API key to post results. Nice thing is we could revoke these keys, and they would be associated with a user. 

In terms of other meta-data, it seems that it would be best if as much meta-data as possible is put into NeuroVault as possible. That way, `fitlins` can come up with a general way to post this information (regardless of which authentication keys are used), and NeuroScout just needs to know this collection exists, and link to it/display it (maybe a POST that analysis is done/uploaded). 

Any NeuroScout specific reports can be handled here (e.g., more about the predictors/extractors/design: https://github.com/neuroscout/neuroscout/issues/478). Although potentially, if NeuroVault expands sufficiently, design information could also be held there (since fitlins also has access to a good amount of that stuff).

**Comment by adelavega** [comment]
@tyarkoni @effigies @rwblair  @chrisfilo

**Comment by effigies** [comment]
Here's a possibility (maybe not technically possible, yet): Each NeuroScout analysis gets a unique NeuroVault token, generated by the NeuroScout backend. That token has a one-time validity, is good only for posting data (if the NeuroVault API allows other operations), and is only used if the analysis runs to completion without error.

**Comment by adelavega** [comment]
That would be nice. 

Although, I do recall @chrisfilo saying the NeuroVault API is not designed to be an authentication server, so I think for a lot of these we'll have to work around the way the API currently works.

**Comment by tyarkoni** [comment]
I think something like @effigies' suggestion could still work nicely in combination with your (2). I.e., all authentication is between NeuroScout and NeuroVault, with NeuroScout acting as a normal user during authentication, and custom extensions on the NeuroVault side handling/presenting the NeuroScout uploads in a more complex way (e.g., displaying the NeuroScout user as the author, and linking to the user's page on NeuroScout).

This is a bit annoying because we have the extra relay step, but provided we can bundle everything up on the client side into an archive format NeuroVault accepts, the extra work should be pretty minimal.

**Comment by adelavega** [comment]
Here's the summary of what we decided to do (after chatting with @tyarkoni):

To have more control, and be able to validate results / reduce burden of uploading, fitlins results will be uploaded back to the NeuroScout API using `pyns`. Authentications will be handled using a salted hash of the analysis ID, and in the future more validation of uploaded contents will be done (e.g. # of images, that this was produced by fitlins, etc..). 

On the API side, the `/upload` results route will spawn a Celery task, which will upload the images to NeuroVault using a neuroscout user. Results will be invisible as to not clog up NeuroVault. Since results can't be displayed on our end, currently they will be only a link to NeuroVault, and privacy will be determined on NeuroScout. Users will not be able to opt out of uploading back to us, so this needs to be added to our TOS. 

This solution doesn't not require any immediate change to NeuroVault.

The long term goal would be for `fitlins` to produce a NIMATS (or whatever its called), `JSON` representation of the result. Generalizatble JSON viewers of this standard ("NeuroView"?) will enable viewing this results report on NeuroScout, as well as for other users of the standard.

**Comment by adelavega** [comment]
Here's the summary of what we decided to do (after chatting with @tyarkoni):

To have more control, and be able to validate results / reduce burden of uploading, fitlins results will be uploaded back to the NeuroScout API using `pyns`. Authentications will be handled using a salted hash of the analysis ID, and in the future more validation of uploaded contents will be done (e.g. # of images, that this was produced by fitlins, etc..). 

On the API side, the `/upload` results route will spawn a Celery task, which will upload the images to NeuroVault using a neuroscout user. Results will be invisible as to not clog up NeuroVault. Since results can't be displayed on our end, currently they will be only a link to NeuroVault, and privacy will be determined on NeuroScout. Users will not be able to opt out of uploading back to us, so this needs to be added to our TOS. 

This solution doesn't not require any immediate change to NeuroVault.

The long term goal would be for `fitlins` to produce a NIMATS (or whatever its called), `JSON` representation of the result. Generalizatble JSON viewers of this standard ("NeuroView"?) will enable viewing this results report on NeuroScout, as well as for other users of the standard.

**Comment by chrisfilo** [comment]
Is there a reason to group all results under `neuroscout` user in NeuroVault? Some users might want to have control over their results (for example make them private or delete them).

BTW I like the idea of `NIMATS`. Even though it is similar to NIDM-Results I think one could come up with a more compact and interoperable representation. Imagine:
- a single 4D nifti file where each volume are different outputs of the analysis (unthresholded map, excursion set, analysis mask, error map etc.)
- metadata is stored in the custom header field of the 4d nifti file

One file includes everything and could be opened by fancy new JS viewers as well as old school nifti viewers.

**Comment by adelavega** [comment]
I agree that would be nice, but the main reason is pragmatic. We don't want to have to force users to log in (or even have a NeuroVault account to begin with), and therefore be able to opt out of uploading their results. By default, the collections would be hidden, and users have the ability to make analyses on NeuroScout public or private. 

One option is to let users manage these collections through NeuroScout (e.g. delete). Perhaps they could take ownership of the collections as well (or clone it), and we could associate their email with the collection in some meta-data field.

Alternatively, we could use the neuroscout account only for users w/o a NeuroVault account. In this scenario, if the NeuroVault API could provide API keys

**Comment by adelavega** [comment]
Closed with #72
