### ISSUE TITLE
Group level model is not being run

### ISSUE THREAD

**Issue by adelavega** [neuroscout/neuroscout-cli#42]
Not sure why, but maybe the JSON is improperly specified.

For example, the following doesn't run the group level model:
```
{
    "blocks": [
      {
        "auto_contrasts": true,
        "contrasts": [],
        "level": "run",
        "model": {
          "HRF_variables": [
            "rmse"
          ],
          "variables": [
            "rmse",
            "FramewiseDisplacement"
          ]
        },
        "transformations": [
          {
            "demean": true,
            "input": [
              "rmse"
            ],
            "name": "scale",
            "rescale": true
          }
        ]
      },
      {
        "auto_contrasts": true,
        "level": "dataset"
      }
    ],
    "description": "My brilliant neuroscout analysis",
    "input": {
      "run": [
        1
      ],
      "subject": [
        "rid000006",
        "rid000009"
      ],
      "task": "life"
    },
    "name": "SmallLittleDemoAnalysis"
}

```

**Comment by effigies** [comment]
Is `"auto_contrasts": true,` valid yet?

**Comment by tyarkoni** [comment]
Yeah I think right now you may have to specify the block for the second level even if it's empty. I don't know that a decision has been made at the spec level yet about which way to go on this, but I lean fairly strongly towards forcing every level to be explicitly included, so if it's failing because of that, I'd consider it a feature at this stage.

**Comment by adelavega** [comment]
The level is included, but the `model` for that level is not included (e.g. inputs, transformations), because there are none. Only contrasts which are automatically created.

**Comment by tyarkoni** [comment]
I see. Yeah the model isn't required, so not sure what's going wrong...

**Comment by adelavega** [comment]
OK Cool. I'll look into it later, just wanted to make a note for now.

**Comment by adelavega** [comment]
@effigies Not sure why but this still doesn't seem to run using the latest `fitlins`. Any ideas?

This is the output of pybids Analysis. Looks good to me. 

```
In [29]: second.get_design_matrix()
Out[29]: 
[DesignMatrixInfo(sparse=   amplitude              condition  run    subject  task
0        1.0             brightness    1  rid000006  life
1        1.0             brightness    1  rid000009  life
2        1.0  FramewiseDisplacement    1  rid000006  life
3        1.0  FramewiseDisplacement    1  rid000009  life, dense=None, entities={'run': 1, 'task': 'life'})]

In [31]: second.get_contrasts()
Out[31]: 
[ContrastMatrixInfo(data=                       brightness  FramewiseDisplacement
brightness                    1.0                    0.0
FramewiseDisplacement         0.0                    1.0
brightness                    1.0                    0.0
FramewiseDisplacement         0.0                    1.0, index=   run    subject  task
0    1  rid000006  life
1    1  rid000006  life
2    1  rid000009  life
3    1  rid000009  life, entities={'run': 1, 'task': 'life'})]
```

**Comment by adelavega** [comment]
Allright, looks like its a different issue now with the latest fitlins release: `l1_metadata` fails. Will look into it tomorrow, but if you had a change to take a look, you could check out analysis `ylb` on Neuroscout @effigies

**Comment by effigies** [comment]
I can take a look. How do I access Neuroscout? "Browse public analyses" does nothing on http://alpha.neuroscout.org and http://neuroscout.org redirects to a missing GitHub Pages site.

**Comment by adelavega** [comment]
Probably good to work this out because I'm sure this won't be the last time we'll be debugging `neuroscout` `fitlins` interactions

Here's the API docs: http://alpha.neuroscout.org/swagger-ui/
And I have written a Python API wrapper: https://github.com/neuroscout/pyns

But more useful is trying the actual `neuroscout-cli` (see README in this repo)

Something like this would run the analysis:

`docker run -it -v /out/folder:/out -v /download/data/here/:/data neuroscout/neuroscout-cli run ylb -o /out`

But maybe its best if you pull from github and build your own image from this branch:
https://github.com/neuroscout/neuroscout-cli/tree/no_bidsconfig

Then build `docker build . -t neuroscout-cli` and run from that image. This is my current working branch to update based on the latest fitlins changes on github. 

Next time you run you can add the `-n` flag so it won't try to download the data again (if you mount the same data directory, that is). 

Ping me on Slack, I'd appreciate it if you gave it a shot!
