### ISSUE TITLE
Setup versions on Docker hub

### ISSUE THREAD

**Issue by adelavega** [neuroscout/neuroscout-cli#62]
Currently, it is just pulling off master, which is pulling off fitlins/master.

Ideally, would pull from fitlins version when pushing to a tagged version, and from master when in a dev branch/unstable release.

@effigies do you mind sharing your Docker Hub setup? I like how fitlins does it

Here is the current one for reference:
![image](https://user-images.githubusercontent.com/2774448/51625114-fa859e80-1f01-11e9-8886-60b6f74fa12d.png)

**Comment by effigies** [comment]
I don't know anything about DockerHub. I just push with Circle:

https://github.com/poldracklab/fitlins/blob/c7cc798330a8fe8cea8ee545c64c7fb08d1a562b/.circleci/config.yml#L101-L103

**Comment by adelavega** [comment]
Ah, so Circle builds your images and simple pushes? Interesting

**Comment by adelavega** [comment]
OK, this has been set to have version tags + a `latest` tag that is mapped to `master` here.
Since Docker Cloud builds need tags, `latest` mapped to the "latest" release is not possible, as that is not a version tag. There is a github link to the latest release, but its not a tag, so it doesn't recognize it.
