### ISSUE TITLE
add verbose/quiet mode cli options

### ISSUE THREAD

**Issue by adelavega** [neuroscout/neuroscout-cli#96]
to pass down to fitlins.

q: what is the default verbosity level?

**Comment by effigies** [comment]
The default level of verbosity I think is warnings. I feel like I should set it a bit higher than, as FitLins is pretty quiet by default so I always add `-v`.

**Comment by adelavega** [comment]
Yeah. I think it used to be verbose by default too right?

Mostly just to get some idea of the progress. We could potentially add some sort of progress bar into fitlins as well, which is less scary for the user.
