### ISSUE TITLE
disable uploading subject files by default?

### ISSUE THREAD

**Issue by adelavega** [neuroscout/neuroscout-cli#97]
When uploading all subject and group level images, for a model with 6 contrasts, in the HBN dataset which has 142 subject, that results in over 4000 individual images being uploaded to NeuroVault.

Each file is about 500MB.

Should we be concerned about this?

This creates a task for each upload in celery, which can hog our resources, and can potentially take up a lot of space on NeuroVault.

I suggest we reduce the number of files uploaded by default for now

cc: @rwblair @tyarkoni

**Comment by tyarkoni** [comment]
I assume you mean 500 MB for each analysis, not each file, but that's still potentially problematic. Actually, even for small datasets, if the model is large, that starts to seem unwieldy. Assume just 1,000 analyses x 20 subjects x 10 regressors x 5 stats x 1 MB/image and we already consume 1 TB.

@rwblair, what (if any) are the storage limits on NeuroVault?

I agree that, at least in the short term, we should probably not upload the subject-level images, but only the group-level ones.

**Comment by adelavega** [comment]
Yes, actually each individual image image is about ~1MB. 

For the HBN dataset, with ~ 142 subjects, it's close to a 1GB per analysis actually. 

We could also limit which images we upload, which would control thatt number a bit. For example, only upload effect and variance images at the subject level (which are useful for meta-analysis). 

Maybe that should be a CLI flag for now, with default "group" but options including: "all", and "none"

**Comment by rwblair** [comment]
No hard limits on storage, instance storage automatically expands as needed. So for now everythings ok, but I need to look into the economics of it to make sure this is sustainable in the long run.
